### ISSUE TITLE
Anyone test it on android？

### ISSUE THREAD

**Issue by imuzi** [askyrme/luaproc#10]
Ndk build is passed，now i met a new problem ，function``` luaproc.newproc``` return true ,but subthread is not running !
It works perfect on ios !
I tried to turn off the luajit on android ,still seems no effective.
Below is the test code !
Ps: I also tested the llthread and llthread2,both met the same problem ,no log info printed.

```lua
 local luaproc = require "luaproc" 
    luaproc.setnumworkers( 1 ) 
    local isSuc = luaproc.newproc([[ 
        print("----luaproc.newproc------")  
        ]]) 
    print("----isSuc------",isSuc)
```

**Comment by askyrme** [comment]
Hello. I have no experience in running luaproc on Android and neither have I received any such reports.

**Comment by imuzi** [comment]
Thanks for shareing the words！
