### ISSUE TITLE
Build iOS Error

### ISSUE THREAD

**Issue by YUTTHANAI** [askyrme/luaproc#15]
Hi.

Today I have a problem when build iOS application and I send console output to here.

Building iOS app for yutthanai.n@gmail.com with 2017.3068

BuildID: 58f8895fee136

Using additional build settings from: /Users/admin/Develop/Mobile App/Corona SDK/AEC Wallet/build.settings

WARNING: iOS builds require iphone.plist.UILaunchStoryboardName or iphone.plist.UILaunchImages in build.settings

Building: Copying app resources

Excluding specified files from build:

excluding: Icon-*dpi.png

Building: Generating Live Build manifest

Building: Unpacking build from server

Building: Adding plugins

Analyzing plugins...

Found native plugin: /Users/admin/Develop/Mobile App/Corona SDK/AEC Wallet.app/.build/plugin.liveBuild

Found native plugin: /Users/admin/Develop/Mobile App/Corona SDK/AEC Wallet.app/.build/plugin.luaproc

Found native plugin: /Users/admin/Develop/Mobile App/Corona SDK/AEC Wallet.app/.build/plugin.OneSignal

Found native plugin: /Users/admin/Develop/Mobile App/Corona SDK/AEC Wallet.app/.build/plugin.openssl

Found native plugin: /Users/admin/Develop/Mobile App/Corona SDK/AEC Wallet.app/.build/plugin.photoLibPlus

Found native plugin: /Users/admin/Develop/Mobile App/Corona SDK/AEC Wallet.app/.build/plugin.utf8

Done.

Analyzing Lua plugins...

Examining plugin: plugin.GBCLanguageCabinet

Found Lua plugin: plugin.GBCLanguageCabinet

Examining plugin: plugin.liveBuild

Examining plugin: plugin.luaproc

Examining plugin: plugin.OneSignal

Examining plugin: plugin.openssl

Examining plugin: plugin.photoLibPlus

Examining plugin: plugin.utf8

<execute>mkdir -p "/Users/admin/Develop/Mobile App/Corona SDK/AEC Wallet.app/corona-plugins"</execute>

<result></result>

<execute>cp -R "/Users/admin/Develop/Mobile App/Corona SDK/AEC Wallet.app/.build/plugin.GBCLanguageCabinet/lua/lua_51/"/* "/Users/admin/Develop/Mobile App/Corona SDK/AEC Wallet.app/corona-plugins"</execute>

<result></result>

<execute>find "/Users/admin/Develop/Mobile App/Corona SDK/AEC Wallet.app/corona-plugins" \( -name '*.lu' -o -name '*.lua' \) -delete</execute>

<result></result>

<execute>COPYPNG=$(xcrun -f copypng); find "/Users/admin/Develop/Mobile App/Corona SDK/AEC Wallet.app/corona-plugins" -name '*.png' -exec "$COPYPNG" -compress {} {}.copypng \; -exec mv {}.copypng {} \;</execute>

<result></result>

Done.

Compiling Slices...

Compiling architecture:armv7

<execute>cd "/var/folders/pz/vwv41d293fsckg6m9j2zz4tw0000gn/T/CLtmpw1imsJ/armv7";unset LIBRARY_PATH; export IPHONEOS_DEPLOYMENT_TARGET=8; export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin/:/Applications/Xcode.app/Contents/Developer/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin";"/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++" -stdlib=libstdc++ -arch armv7 -isysroot "/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS10.3.sdk" -ObjC -all_load -fobjc-link-runtime -miphoneos-version-min=8 -std=c++11 -stdlib=libc++ -Xlinker -rpath -Xlinker @executable_path/Frameworks -L"/Users/admin/Develop/Mobile App/Corona SDK/AEC Wallet.app/.build/libtemplate" -L"/Users/admin/Develop/Mobile App/Corona SDK/AEC Wallet.app/.build/plugin.liveBuild" -L"/Users/admin/Develop/Mobile App/Corona SDK/AEC Wallet.app/.build/plugin.luaproc" -L"/Users/admin/Develop/Mobile App/Corona SDK/AEC Wallet.app/.build/plugin.OneSignal" -L"/Users/admin/Develop/Mobile App/Corona SDK/AEC Wallet.app/.build/plugin.openssl" -L"/Users/admin/Develop/Mobile App/Corona SDK/AEC Wallet.app/.build/plugin.photoLibPlus" -L"/Users/admin/Develop/Mobile App/Corona SDK/AEC Wallet.app/.build/plugin.utf8" -F"/Users/admin/Develop/Mobile App/Corona SDK/AEC Wallet.app/Frameworks" -framework AudioToolbox -framework AVFoundation -framework CFNetwork -framework CoreGraphics -framework CoreLocation -framework CoreMedia -framework CoreMotion -framework CoreVideo -framework CoreText -framework GameKit -framework GLKit -framework ImageIO -framework MapKit -framework MediaPlayer -framework MessageUI -framework MobileCoreServices -framework OpenAL -framework OpenGLES -framework QuartzCore -framework Security -framework StoreKit -framework SystemConfiguration -framework UIKit -weak_framework GameController -weak_framework AssetsLibrary -weak_framework Photos -weak_framework Foundation -weak_framework Twitter -lobjc -lsqlite3 -ltemplate -lplugin_liveBuild -lplugin_luaproc -lplugin_OneSignal -lplugin.openssl -lphotoLibPlus -lplugin.utf8 -o "/var/folders/pz/vwv41d293fsckg6m9j2zz4tw0000gn/T/CLtmpw1imsJ/armv7/AEC Wallet"</execute>

<result>ld: warning: directory not found for option '-F/Users/admin/Develop/Mobile App/Corona SDK/AEC Wallet.app/Frameworks'

Undefined symbols for architecture armv7:

"std::string::_Rep::_M_destroy(std::allocator<char> const&)", referenced from:

_AddInteger in libplugin_luaproc.a(extensions.o)

_AddNumber in libplugin_luaproc.a(extensions.o)

_RemoveInteger in libplugin_luaproc.a(extensions.o)

_RemoveNumber in libplugin_luaproc.a(extensions.o)

_PopFunction in libplugin_luaproc.a(extensions.o)

_CreateEventX in libplugin_luaproc.a(extensions.o)

_DestroyEventX in libplugin_luaproc.a(extensions.o)

...

"std::string::_Rep::_S_empty_rep_storage", referenced from:

_AddInteger in libplugin_luaproc.a(extensions.o)

_AddNumber in libplugin_luaproc.a(extensions.o)

_RemoveInteger in libplugin_luaproc.a(extensions.o)

_RemoveNumber in libplugin_luaproc.a(extensions.o)

_PopFunction in libplugin_luaproc.a(extensions.o)

_CreateEventX in libplugin_luaproc.a(extensions.o)

_DestroyEventX in libplugin_luaproc.a(extensions.o)

...

"std::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string(char const*, std::allocator<char> const&)", referenced from:

_AddInteger in libplugin_luaproc.a(extensions.o)

_AddNumber in libplugin_luaproc.a(extensions.o)

_RemoveInteger in libplugin_luaproc.a(extensions.o)

_RemoveNumber in libplugin_luaproc.a(extensions.o)

_PopFunction in libplugin_luaproc.a(extensions.o)

_CreateEventX in libplugin_luaproc.a(extensions.o)

_DestroyEventX in libplugin_luaproc.a(extensions.o)

...

"std::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string(std::string const&)", referenced from:

AddFunction::$_5::__invoke(void*) in libplugin_luaproc.a(extensions.o)

std::tr1::__detail::_Map_base<std::string, std::pair<std::string const, Entry>, std::_Select1st<std::pair<std::string const, Entry> >, true, std::tr1::_Hashtable<std::string, std::pair<std::string const, Entry>, std::allocator<std::pair<std::string const, Entry> >, std::_Select1st<std::pair<std::string const, Entry> >, std::equal_to<std::string>, std::tr1::hash<std::string>, std::tr1::__detail::_Mod_range_hashing, std::tr1::__detail::_Default_ranged_hash, std::tr1::__detail::_Prime_rehash_policy, false, false, true> >::operator[](std::string const&) in libplugin_luaproc.a(extensions.o)

std::tr1::_Hashtable<std::string, std::pair<std::string const, Entry>, std::allocator<std::pair<std::string const, Entry> >, std::_Select1st<std::pair<std::string const, Entry> >, std::equal_to<std::string>, std::tr1::hash<std::string>, std::tr1::__detail::_Mod_range_hashing, std::tr1::__detail::_Default_ranged_hash, std::tr1::__detail::_Prime_rehash_policy, false, false, true>::_M_allocate_node(std::pair<std::string const, Entry> const&) in libplugin_luaproc.a(extensions.o)

ld: symbol(s) not found for architecture armv7

clang: error: linker command failed with exit code 1 (use -v to see invocation)</result>

ERROR: Builder failed: ld: warning: directory not found for option '-F/Users/admin/Develop/Mobile App/Corona SDK/AEC Wallet.app/Frameworks'

Undefined symbols for architecture armv7:

"std::string::_Rep::_M_destroy(std::allocator<char> const&)", referenced from:

_AddInteger in libplugin_luaproc.a(extensions.o)

_AddNumber in libplugin_luaproc.a(extensions.o)

_RemoveInteger in libplugin_luaproc.a(extensions.o)

_RemoveNumber in libplugin_luaproc.a(extensions.o)

_PopFunction in libplugin_luaproc.a(extensions.o)

_CreateEventX in libplugin_luaproc.a(extensions.o)

_DestroyEventX in libplugin_luaproc.a(extensions.o)

...

"std::string::_Rep::_S_empty_rep_storage", referenced from:

_AddInteger in libplugin_luaproc.a(extensions.o)

_AddNumber in libplugin_luaproc.a(extensions.o)

_RemoveInteger in libplugin_luaproc.a(extensions.o)

_RemoveNumber in libplugin_luaproc.a(extensions.o)

_PopFunction in libplugin_luaproc.a(extensions.o)

_CreateEventX in libplugin_luaproc.a(extensions.o)

_DestroyEventX in libplugin_luaproc.a(extensions.o)

...

"std::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string(char const*, std::allocator<char> const&)", referenced from:

_AddInteger in libplugin_luaproc.a(extensions.o)

_AddNumber in libplugin_luaproc.a(extensions.o)

_RemoveInteger in libplugin_luaproc.a(extensions.o)

_RemoveNumber in libplugin_luaproc.a(extensions.o)

_PopFunction in libplugin_luaproc.a(extensions.o)

_CreateEventX in libplugin_luaproc.a(extensions.o)

_DestroyEventX in libplugin_luaproc.a(extensions.o)

...

"std::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string(std::string const&)", referenced from:

AddFunction::$_5::__invoke(void*) in libplugin_luaproc.a(extensions.o)

std::tr1::__detail::_Map_base<std::string, std::pair<std::string const, Entry>, std::_Select1st<std::pair<std::string const, Entry> >, true, std::tr1::_Hashtable<std::string, std::pair<std::string const, Entry>, std::allocator<std::pair<std::string const, Entry> >, std::_Select1st<std::pair<std::string const, Entry> >, std::equal_to<std::string>, std::tr1::hash<std::string>, std::tr1::__detail::_Mod_range_hashing, std::tr1::__detail::_Default_ranged_hash, std::tr1::__detail::_Prime_rehash_policy, false, false, true> >::operator[](std::string const&) in libplugin_luaproc.a(extensions.o)

std::tr1::_Hashtable<std::string, std::pair<std::string const, Entry>, std::allocator<std::pair<std::string const, Entry> >, std::_Select1st<std::pair<std::string const, Entry> >, std::equal_to<std::string>, std::tr1::hash<std::string>, std::tr1::__detail::_Mod_range_hashing, std::tr1::__detail::_Default_ranged_hash, std::tr1::__detail::_Prime_rehash_policy, false, false, true>::_M_allocate_node(std::pair<std::string const, Entry> const&) in libplugin_luaproc.a(extensions.o)

ld: symbol(s) not found for architecture armv7

clang: error: linker command failed with exit code 1 (use -v to see invocation)

BUILD ERROR: There was a problem linking the app.

Check the console for more information.

iOS build failed (12) after 126 seconds

ERROR: Build Failed: There was a problem linking the app.

———————————————————

I don’t know what happen. Please advice to me. 
(Android is find.)

Thank you

Yutthanai Nitipisuttikul

E-Customs Service Co.,Ltd.

**Comment by askyrme** [comment]
luaproc has only been tested in Linux.
