### ISSUE TITLE
"Still reachable objects" at the end of execution

### ISSUE THREAD

**Issue by pmusa** [askyrme/luaproc#4]
Executing simple test does not free all blocks. It is probably related to pthreads.

==17390== Memcheck, a memory error detector
==17390== Copyright (C) 2002-2013, and GNU GPL'd, by Julian Seward et al.
==17390== Using Valgrind-3.10.0.SVN and LibVEX; rerun with -h for copyright info
==17390== Command: lua tests/hello.lua
==17390== 
hello world from luaproc
==17390== 
==17390== HEAP SUMMARY:
==17390==     in use at exit: 3,362 bytes in 9 blocks
==17390==   total heap usage: 1,090 allocs, 1,081 frees, 107,007 bytes allocated
==17390== 
==17390== 32 bytes in 1 blocks are still reachable in loss record 1 of 9
==17390==    at 0x4C2AB80: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==17390==    by 0x4015DB8: _dl_close_worker (dl-close.c:379)
==17390==    by 0x401648B: _dl_close (dl-close.c:773)
==17390==    by 0x400FFF3: _dl_catch_error (dl-error.c:187)
==17390==    by 0x513E62C: _dlerror_run (dlerror.c:163)
==17390==    by 0x513E10E: dlclose (dlclose.c:46)
==17390==    by 0x4204B3: ??? (in /usr/bin/lua5.2)
==17390==    by 0x4081AC: ??? (in /usr/bin/lua5.2)
==17390==    by 0x4084FC: ??? (in /usr/bin/lua5.2)
==17390==    by 0x407B48: ??? (in /usr/bin/lua5.2)
==17390==    by 0x408740: ??? (in /usr/bin/lua5.2)
==17390==    by 0x409826: ??? (in /usr/bin/lua5.2)
==17390== 
==17390== 36 bytes in 1 blocks are still reachable in loss record 2 of 9
==17390==    at 0x4C2AB80: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==17390==    by 0x4009123: _dl_map_object (dl-load.c:162)
==17390==    by 0x4014A53: dl_open_worker (dl-open.c:235)
==17390==    by 0x400FFF3: _dl_catch_error (dl-error.c:187)
==17390==    by 0x40143BA: _dl_open (dl-open.c:661)
==17390==    by 0x56BDC31: do_dlopen (dl-libc.c:87)
==17390==    by 0x400FFF3: _dl_catch_error (dl-error.c:187)
==17390==    by 0x56BDCF1: __libc_dlopen_mode (dl-libc.c:46)
==17390==    by 0x618DA42: pthread_cancel_init (unwind-forcedunwind.c:52)
==17390==    by 0x618DC0B: _Unwind_ForcedUnwind (unwind-forcedunwind.c:129)
==17390==    by 0x618BD3F: __pthread_unwind (unwind.c:129)
==17390==    by 0x6186534: pthread_exit (pthreadP.h:280)
==17390== 
==17390== 36 bytes in 1 blocks are still reachable in loss record 3 of 9
==17390==    at 0x4C2AB80: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==17390==    by 0x400BDC3: _dl_new_object (dl-object.c:165)
==17390==    by 0x4006783: _dl_map_object_from_fd (dl-load.c:1059)
==17390==    by 0x4008DFF: _dl_map_object (dl-load.c:2605)
==17390==    by 0x4014A53: dl_open_worker (dl-open.c:235)
==17390==    by 0x400FFF3: _dl_catch_error (dl-error.c:187)
==17390==    by 0x40143BA: _dl_open (dl-open.c:661)
==17390==    by 0x56BDC31: do_dlopen (dl-libc.c:87)
==17390==    by 0x400FFF3: _dl_catch_error (dl-error.c:187)
==17390==    by 0x56BDCF1: __libc_dlopen_mode (dl-libc.c:46)
==17390==    by 0x618DA42: pthread_cancel_init (unwind-forcedunwind.c:52)
==17390==    by 0x618DC0B: _Unwind_ForcedUnwind (unwind-forcedunwind.c:129)
==17390== 
==17390== 38 bytes in 1 blocks are still reachable in loss record 4 of 9
==17390==    at 0x4C2AB80: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==17390==    by 0x4009123: _dl_map_object (dl-load.c:162)
==17390==    by 0x400D601: openaux (dl-deps.c:63)
==17390==    by 0x400FFF3: _dl_catch_error (dl-error.c:187)
==17390==    by 0x400DD04: _dl_map_object_deps (dl-deps.c:254)
==17390==    by 0x4014AAA: dl_open_worker (dl-open.c:272)
==17390==    by 0x400FFF3: _dl_catch_error (dl-error.c:187)
==17390==    by 0x40143BA: _dl_open (dl-open.c:661)
==17390==    by 0x513E02A: dlopen_doit (dlopen.c:66)
==17390==    by 0x400FFF3: _dl_catch_error (dl-error.c:187)
==17390==    by 0x513E62C: _dlerror_run (dlerror.c:163)
==17390==    by 0x513E0C0: dlopen@@GLIBC_2.2.5 (dlopen.c:87)
==17390== 
==17390== 38 bytes in 1 blocks are still reachable in loss record 5 of 9
==17390==    at 0x4C2AB80: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==17390==    by 0x400BDC3: _dl_new_object (dl-object.c:165)
==17390==    by 0x4006783: _dl_map_object_from_fd (dl-load.c:1059)
==17390==    by 0x4008DFF: _dl_map_object (dl-load.c:2605)
==17390==    by 0x400D601: openaux (dl-deps.c:63)
==17390==    by 0x400FFF3: _dl_catch_error (dl-error.c:187)
==17390==    by 0x400DD04: _dl_map_object_deps (dl-deps.c:254)
==17390==    by 0x4014AAA: dl_open_worker (dl-open.c:272)
==17390==    by 0x400FFF3: _dl_catch_error (dl-error.c:187)
==17390==    by 0x40143BA: _dl_open (dl-open.c:661)
==17390==    by 0x513E02A: dlopen_doit (dlopen.c:66)
==17390==    by 0x400FFF3: _dl_catch_error (dl-error.c:187)
==17390== 
==17390== 360 bytes in 1 blocks are still reachable in loss record 6 of 9
==17390==    at 0x4C2CC70: calloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==17390==    by 0x40118A2: _dl_check_map_versions (dl-version.c:293)
==17390==    by 0x4014EEC: dl_open_worker (dl-open.c:278)
==17390==    by 0x400FFF3: _dl_catch_error (dl-error.c:187)
==17390==    by 0x40143BA: _dl_open (dl-open.c:661)
==17390==    by 0x56BDC31: do_dlopen (dl-libc.c:87)
==17390==    by 0x400FFF3: _dl_catch_error (dl-error.c:187)
==17390==    by 0x56BDCF1: __libc_dlopen_mode (dl-libc.c:46)
==17390==    by 0x618DA42: pthread_cancel_init (unwind-forcedunwind.c:52)
==17390==    by 0x618DC0B: _Unwind_ForcedUnwind (unwind-forcedunwind.c:129)
==17390==    by 0x618BD3F: __pthread_unwind (unwind.c:129)
==17390==    by 0x6186534: pthread_exit (pthreadP.h:280)
==17390== 
==17390== 456 bytes in 1 blocks are still reachable in loss record 7 of 9
==17390==    at 0x4C2CC70: calloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==17390==    by 0x40118A2: _dl_check_map_versions (dl-version.c:293)
==17390==    by 0x4014EEC: dl_open_worker (dl-open.c:278)
==17390==    by 0x400FFF3: _dl_catch_error (dl-error.c:187)
==17390==    by 0x40143BA: _dl_open (dl-open.c:661)
==17390==    by 0x513E02A: dlopen_doit (dlopen.c:66)
==17390==    by 0x400FFF3: _dl_catch_error (dl-error.c:187)
==17390==    by 0x513E62C: _dlerror_run (dlerror.c:163)
==17390==    by 0x513E0C0: dlopen@@GLIBC_2.2.5 (dlopen.c:87)
==17390==    by 0x4202A9: ??? (in /usr/bin/lua5.2)
==17390==    by 0x4208CB: ??? (in /usr/bin/lua5.2)
==17390==    by 0x4081AC: ??? (in /usr/bin/lua5.2)
==17390== 
==17390== 1,182 bytes in 1 blocks are still reachable in loss record 8 of 9
==17390==    at 0x4C2CC70: calloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==17390==    by 0x400BB23: _dl_new_object (dl-object.c:75)
==17390==    by 0x4006783: _dl_map_object_from_fd (dl-load.c:1059)
==17390==    by 0x4008DFF: _dl_map_object (dl-load.c:2605)
==17390==    by 0x4014A53: dl_open_worker (dl-open.c:235)
==17390==    by 0x400FFF3: _dl_catch_error (dl-error.c:187)
==17390==    by 0x40143BA: _dl_open (dl-open.c:661)
==17390==    by 0x56BDC31: do_dlopen (dl-libc.c:87)
==17390==    by 0x400FFF3: _dl_catch_error (dl-error.c:187)
==17390==    by 0x56BDCF1: __libc_dlopen_mode (dl-libc.c:46)
==17390==    by 0x618DA42: pthread_cancel_init (unwind-forcedunwind.c:52)
==17390==    by 0x618DC0B: _Unwind_ForcedUnwind (unwind-forcedunwind.c:129)
==17390== 
==17390== 1,184 bytes in 1 blocks are still reachable in loss record 9 of 9
==17390==    at 0x4C2CC70: calloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==17390==    by 0x400BB23: _dl_new_object (dl-object.c:75)
==17390==    by 0x4006783: _dl_map_object_from_fd (dl-load.c:1059)
==17390==    by 0x4008DFF: _dl_map_object (dl-load.c:2605)
==17390==    by 0x400D601: openaux (dl-deps.c:63)
==17390==    by 0x400FFF3: _dl_catch_error (dl-error.c:187)
==17390==    by 0x400DD04: _dl_map_object_deps (dl-deps.c:254)
==17390==    by 0x4014AAA: dl_open_worker (dl-open.c:272)
==17390==    by 0x400FFF3: _dl_catch_error (dl-error.c:187)
==17390==    by 0x40143BA: _dl_open (dl-open.c:661)
==17390==    by 0x513E02A: dlopen_doit (dlopen.c:66)
==17390==    by 0x400FFF3: _dl_catch_error (dl-error.c:187)
==17390== 
==17390== LEAK SUMMARY:
==17390==    definitely lost: 0 bytes in 0 blocks
==17390==    indirectly lost: 0 bytes in 0 blocks
==17390==      possibly lost: 0 bytes in 0 blocks
==17390==    still reachable: 3,362 bytes in 9 blocks
==17390==         suppressed: 0 bytes in 0 blocks
==17390== 
==17390== For counts of detected and suppressed errors, rerun with: -v
==17390== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)

**Comment by askyrme** [comment]
So far there is no evidence that there are memory leaks (other than the ones that were already fixed :-)). It should be related to pthreads indeed.
