### ISSUE TITLE
Makefile minor "errors"

### ISSUE THREAD

**Issue by pmusa** [askyrme/luaproc#5]
By default Lua searches inside "lib" for .so libs and not share.
Besides, libname.so are placed in the root not folder, not in a sub-folder.

\# path to install library
< LUA_CPATH=/usr/share/lua/${LUA_VERSION}
> LUA_CPATH=/usr/lib/lua/${LUA_VERSION}

install:
<        mkdir -p ${LUA_CPATH}/${LIBNAME} 
<        cp -v bin/${LIB} ${LUA_CPATH}/${LIBNAME}

>        cp -v bin/${LIB} ${LUA_CPATH}/

**Comment by askyrme** [comment]
Thanks, will be included, among other Makefile improvements, in the next upcoming release.
